// Unified Exhibition Booth Layout Data
// 쉽게 수정할 수 있는 단일 통합 데이터 세트 (ID, 상호명, 구역/그룹, 그리드 좌표 및 크기)
const EXHIBITORS_DATA = [
  { id: "A7", name: "(사)세계기독교차문화협회 / 일양차문화연구원 회원 티플라워(다화) 전시회", gridX: 0, gridY: 9, gridW: 1, gridH: 5 },
  { id: "A48", name: "(사)한국 싱잉볼 협회 / (주)젠테라피 네츄럴 힐링센터", gridX: 31, gridY: 7, gridW: 1, gridH: 2 },
  { id: "H21", name: "(주)차모아", gridX: 27, gridY: 21, gridW: 2, gridH: 1 },
  { id: "F32", name: "HaDa design(하다디자인)", gridX: 21, gridY: 24, gridW: 1, gridH: 1 },
  { id: "F3", name: "Tea진공밀폐용기 에스락", gridX: 20, gridY: 3, gridW: 1, gridH: 1 },
  { id: "H11", name: "ㄷㅓㄱㅎㅗㅏ(덕화코리아)", gridX: 29, gridY: 11, gridW: 1, gridH: 1 },
  { id: "G18", name: "北京妙香缘贸易有限公司 (북경묘향연무역유한공사)", gridX: 23, gridY: 18, gridW: 1, gridH: 1 },
  { id: "G17", name: "宜兴永盛陶艺茗壶堂 (의흥영성도예명호당)", gridX: 23, gridY: 17, gridW: 1, gridH: 1 },
  { id: "H16", name: "宜兴知了文化创意有限公司 (의흥지료문화창의유한공사)", gridX: 27, gridY: 17, gridW: 1, gridH: 1 },
  { id: "G21", name: "尹茶人-YIN TEA (윤차인)", gridX: 25, gridY: 20, gridW: 1, gridH: 1 },
  { id: "H19", name: "森桦陶瓷公司 (삼화도자기회사)", gridX: 27, gridY: 20, gridW: 1, gridH: 1 },
  { id: "H13", name: "茗扬天下 x 휴코퍼레이션 x 북경도사 (명양천하)", gridX: 27, gridY: 14, gridW: 2, gridH: 2 },
  { id: "F14", name: "가람도예", gridX: 21, gridY: 11, gridW: 1, gridH: 1 },
  { id: "B24", name: "가마공방", gridX: 9, gridY: 21, gridW: 1, gridH: 1 },
  { id: "A17", name: "가헌아트", gridX: 3, gridY: 14, gridW: 1, gridH: 1 },
  { id: "F6", name: "강동현", gridX: 21, gridY: 5, gridW: 1, gridH: 1 },
  { id: "E4", name: "경기한방꽃차협동조합", gridX: 18, gridY: 3, gridW: 1, gridH: 1 },
  { id: "F2", name: "경위복차 (가인갤러리)", gridX: 21, gridY: 2, gridW: 1, gridH: 1 },
  { id: "A24", name: "경주 남촌도예", gridX: 6, gridY: 20, gridW: 1, gridH: 1 },
  { id: "H26", name: "계절사이로(이오순 금침명인)", gridX: 28, gridY: 24, gridW: 1, gridH: 1 },
  { id: "F15", name: "고도산방", gridX: 20, gridY: 12, gridW: 1, gridH: 1 },
  { id: "H25", name: "고전문화", gridX: 27, gridY: 24, gridW: 1, gridH: 1 },
  { id: "D2", name: "곡천다원", gridX: 15, gridY: 2, gridW: 1, gridH: 1 },
  { id: "D25", name: "공림요", gridX: 14, gridY: 20, gridW: 1, gridH: 1 },
  { id: "A9", name: "공부차파크 복합치유공간 (과천 청계산점)", gridX: 2, gridY: 11, gridW: 2, gridH: 1 },
  { id: "D12", name: "관아수제차", gridX: 15, gridY: 9, gridW: 1, gridH: 1 },
  { id: "F5", name: "교문공방", gridX: 20, gridY: 5, gridW: 1, gridH: 1 },
  { id: "A10", name: "국제통상", gridX: 2, gridY: 12, gridW: 1, gridH: 1 },
  { id: "A28", name: "귀단요 성탄송운", gridX: 8, gridY: 26, gridW: 1, gridH: 1 },
  { id: "G5", name: "글림피스", gridX: 25, gridY: 6, gridW: 1, gridH: 1 },
  { id: "D15", name: "금향다원", gridX: 14, gridY: 12, gridW: 1, gridH: 1 },
  { id: "E23", name: "긍정공방", gridX: 17, gridY: 18, gridW: 1, gridH: 1 },
  { id: "D33", name: "기린공방", gridX: 15, gridY: 24, gridW: 1, gridH: 1 },
  { id: "D29", name: "김동인", gridX: 15, gridY: 21, gridW: 1, gridH: 1 },
  { id: "E21", name: "김묘진", gridX: 17, gridY: 17, gridW: 1, gridH: 1 },
  { id: "E2", name: "김천방짜유기 명인 이운형", gridX: 18, gridY: 2, gridW: 1, gridH: 1 },
  { id: "E15", name: "김해예인요", gridX: 17, gridY: 12, gridW: 1, gridH: 1 },
  { id: "F17", name: "김해요", gridX: 20, gridY: 14, gridW: 1, gridH: 1 },
  { id: "A40", name: "꼬매", gridX: 31, gridY: 26, gridW: 1, gridH: 1 },
  { id: "H23", name: "나은크래프트", gridX: 27, gridY: 23, gridW: 1, gridH: 1 },
  { id: "C1", name: "나주", gridX: 11, gridY: 2, gridW: 2, gridH: 2 },
  { id: "F9", name: "날빛", gridX: 20, gridY: 8, gridW: 1, gridH: 1 },
  { id: "C14", name: "노전요", gridX: 11, gridY: 14, gridW: 1, gridH: 1 },
  { id: "D22", name: "녹주요", gridX: 15, gridY: 17, gridW: 1, gridH: 1 },
  { id: "D13", name: "농업회사법인 지리산 상선암차", gridX: 14, gridY: 11, gridW: 1, gridH: 1 },
  { id: "C18", name: "누보도예", gridX: 11, gridY: 17, gridW: 1, gridH: 1 },
  { id: "G10", name: "다견원", gridX: 23, gridY: 11, gridW: 1, gridH: 1 },
  { id: "F18", name: "다경요", gridX: 21, gridY: 14, gridW: 1, gridH: 1 },
  { id: "E16", name: "다솜공방", gridX: 18, gridY: 12, gridW: 1, gridH: 1 },
  { id: "G25", name: "다심헌.AFTR", gridX: 24, gridY: 23, gridW: 2, gridH: 1 },
  { id: "G7", name: "다연재", gridX: 23, gridY: 9, gridW: 1, gridH: 1 },
  { id: "B11", name: "다채", gridX: 9, gridY: 9, gridW: 1, gridH: 1 },
  { id: "B26", name: "대광도요", gridX: 9, gridY: 23, gridW: 1, gridH: 1 },
  { id: "A36", name: "대림목공예", gridX: 23, gridY: 26, gridW: 1, gridH: 1 },
  { id: "G1", name: "대익코리아", gridX: 23, gridY: 2, gridW: 3, gridH: 2 },
  { id: "E1", name: "대통령 표창 수상_꽃차 하늘바라기", gridX: 17, gridY: 2, gridW: 1, gridH: 1 },
  { id: "E25", name: "더셰드", gridX: 17, gridY: 20, gridW: 1, gridH: 1 },
  { id: "B27", name: "도농도예", gridX: 8, gridY: 24, gridW: 1, gridH: 1 },
  { id: "E28", name: "도동요", gridX: 17, gridY: 23, gridW: 1, gridH: 1 },
  { id: "E24", name: "도예명장2023-01호 영산요", gridX: 18, gridY: 18, gridW: 1, gridH: 1 },
  { id: "D23", name: "도유가", gridX: 14, gridY: 18, gridW: 1, gridH: 1 },
  { id: "C17", name: "도자기마을(빛살)", gridX: 12, gridY: 15, gridW: 1, gridH: 1 },
  { id: "D11", name: "도재명차", gridX: 14, gridY: 9, gridW: 1, gridH: 1 },
  { id: "B25", name: "도정요", gridX: 8, gridY: 23, gridW: 1, gridH: 1 },
  { id: "A16", name: "동국대학교 불교대학원 차문화콘텐츠학과", gridX: 2, gridY: 14, gridW: 1, gridH: 1 },
  { id: "G19", name: "동심명차", gridX: 24, gridY: 17, gridW: 2, gridH: 2 },
  { id: "A20", name: "동원공방", gridX: 2, gridY: 15, gridW: 2, gridH: 1 },
  { id: "G15", name: "동정보이차 노반차품", gridX: 23, gridY: 15, gridW: 1, gridH: 1 },
  { id: "F28", name: "드내뜰(이종주의 도자기)", gridX: 21, gridY: 21, gridW: 1, gridH: 1 },
  { id: "E7", name: "따티 (뷰닉스테크)", gridX: 17, gridY: 6, gridW: 1, gridH: 1 },
  { id: "B23", name: "뚜띨로공방", gridX: 8, gridY: 21, gridW: 1, gridH: 1 },
  { id: "F16", name: "라세라미스타", gridX: 21, gridY: 12, gridW: 1, gridH: 1 },
  { id: "C27", name: "라키모", gridX: 12, gridY: 23, gridW: 1, gridH: 1 },
  { id: "G12", name: "랑카티스(스리랑카 홍차)", gridX: 23, gridY: 12, gridW: 1, gridH: 1 },
  { id: "C6", name: "로전", gridX: 11, gridY: 8, gridW: 2, gridH: 1 },
  { id: "A26", name: "매원초가", gridX: 6, gridY: 23, gridW: 1, gridH: 2 },
  { id: "D7", name: "명성다원", gridX: 14, gridY: 6, gridW: 1, gridH: 1 },
  { id: "A12", name: "명인신광수차_무드를 즐기는차(moocha)", gridX: 5, gridY: 11, gridW: 1, gridH: 1 },
  { id: "F25", name: "모동도예", gridX: 20, gridY: 20, gridW: 1, gridH: 1 },
  { id: "F31", name: "모을 황선회도방", gridX: 20, gridY: 24, gridW: 1, gridH: 1 },
  { id: "A13", name: "모후실에서만난차", gridX: 6, gridY: 11, gridW: 1, gridH: 1 },
  { id: "B21", name: "몽탄갤러리", gridX: 8, gridY: 20, gridW: 1, gridH: 1 },
  { id: "F4", name: "묘차", gridX: 21, gridY: 3, gridW: 1, gridH: 1 },
  { id: "B20", name: "무결", gridX: 9, gridY: 18, gridW: 1, gridH: 1 },
  { id: "E13", name: "무무요", gridX: 17, gridY: 11, gridW: 1, gridH: 1 },
  { id: "D14", name: "무애(MUAE TEA)", gridX: 15, gridY: 11, gridW: 1, gridH: 1 },
  { id: "F11", name: "무유", gridX: 20, gridY: 9, gridW: 1, gridH: 1 },
  { id: "A1", name: "무유다원", gridX: 6, gridY: 2, gridW: 1, gridH: 1 },
  { id: "A11", name: "무유장작가마 살래요", gridX: 3, gridY: 12, gridW: 1, gridH: 1 },
  { id: "C26", name: "문경 경북요", gridX: 11, gridY: 23, gridW: 1, gridH: 1 },
  { id: "A15", name: "문경칠봉산농원", gridX: 6, gridY: 12, gridW: 1, gridH: 1 },
  { id: "A23", name: "문재필 옻칠갤러리", gridX: 6, gridY: 18, gridW: 1, gridH: 2 },
  { id: "D20", name: "민토(최민록)", gridX: 15, gridY: 15, gridW: 1, gridH: 1 },
  { id: "H9", name: "밀밀홍", gridX: 29, gridY: 9, gridW: 1, gridH: 1 },
  { id: "G24", name: "바이에드가", gridX: 23, gridY: 23, gridW: 1, gridH: 1 },
  { id: "F24", name: "박달요", gridX: 21, gridY: 18, gridW: 1, gridH: 1 },
  { id: "H27", name: "반짇고리", gridX: 29, gridY: 24, gridW: 1, gridH: 1 },
  { id: "E9", name: "백산도예 연구소", gridX: 17, gridY: 8, gridW: 1, gridH: 1 },
  { id: "E27", name: "백암요", gridX: 18, gridY: 20, gridW: 1, gridH: 2 },
  { id: "A14", name: "백자일상", gridX: 5, gridY: 12, gridW: 1, gridH: 1 },
  { id: "C12", name: "백학제다", gridX: 11, gridY: 12, gridW: 1, gridH: 1 },
  { id: "C21", name: "보니다", gridX: 12, gridY: 18, gridW: 1, gridH: 1 },
  { id: "G26", name: "보림원목 공방", gridX: 23, gridY: 24, gridW: 1, gridH: 1 },
  { id: "B7", name: "보성(부광녹차)", gridX: 9, gridY: 6, gridW: 1, gridH: 1 },
  { id: "B9", name: "보성 영천다원", gridX: 9, gridY: 8, gridW: 1, gridH: 1 },
  { id: "B4", name: "보성 유기농 운해다원", gridX: 8, gridY: 5, gridW: 1, gridH: 1 },
  { id: "B1", name: "보성군 홍보관", gridX: 8, gridY: 2, gridW: 2, gridH: 1 },
  { id: "B12", name: "보성녹차 선다원", gridX: 8, gridY: 11, gridW: 1, gridH: 1 },
  { id: "B2", name: "보성제다", gridX: 8, gridY: 3, gridW: 1, gridH: 1 },
  { id: "A41", name: "보성천연염색협동조합 (자연담은 하늘수)", gridX: 31, gridY: 24, gridW: 1, gridH: 1 },
  { id: "H1", name: "보이차전문점 명가원", gridX: 27, gridY: 2, gridW: 2, gridH: 2 },
  { id: "H6", name: "복향명차", gridX: 29, gridY: 6, gridW: 1, gridH: 1 },
  { id: "C29", name: "봉정요", gridX: 12, gridY: 24, gridW: 1, gridH: 1 },
  { id: "E20", name: "부산광역시 공예협동조합 다솔도예", gridX: 18, gridY: 15, gridW: 1, gridH: 1 },
  { id: "E18", name: "부산광역시 공예협동조합 토산요", gridX: 18, gridY: 14, gridW: 1, gridH: 1 },
  { id: "C13", name: "붓당골제다", gridX: 12, gridY: 12, gridW: 1, gridH: 1 },
  { id: "C25", name: "삐딱한 도자기 황제요", gridX: 12, gridY: 21, gridW: 1, gridH: 1 },
  { id: "G14", name: "사계다향", gridX: 23, gridY: 14, gridW: 1, gridH: 1 },
  { id: "D17", name: "산도방", gridX: 14, gridY: 14, gridW: 1, gridH: 1 },
  { id: "C19", name: "산이리", gridX: 12, gridY: 17, gridW: 1, gridH: 1 },
  { id: "D6", name: "삼신차 (발효차 전문다원)", gridX: 15, gridY: 5, gridW: 1, gridH: 1 },
  { id: "F12", name: "삼정공방", gridX: 21, gridY: 9, gridW: 1, gridH: 1 },
  { id: "H7", name: "상명", gridX: 27, gridY: 8, gridW: 2, gridH: 2 },
  { id: "G22", name: "상해구산지진차문화유한공사", gridX: 23, gridY: 21, gridW: 1, gridH: 1 },
  { id: "H10", name: "석가명차 오운산고차", gridX: 27, gridY: 11, gridW: 2, gridH: 2 },
  { id: "H5", name: "선묘당 (善妙堂) CHINA TEA", gridX: 29, gridY: 5, gridW: 1, gridH: 1 },
  { id: "D18", name: "설도예", gridX: 15, gridY: 14, gridW: 1, gridH: 1 },
  { id: "B13", name: "섬진다원", gridX: 9, gridY: 11, gridW: 1, gridH: 1 },
  { id: "D24", name: "소랑요", gridX: 15, gridY: 18, gridW: 1, gridH: 1 },
  { id: "C24", name: "소산도예", gridX: 11, gridY: 21, gridW: 1, gridH: 1 },
  { id: "B10", name: "소아다원", gridX: 8, gridY: 9, gridW: 1, gridH: 1 },
  { id: "F26", name: "소월백자", gridX: 21, gridY: 20, gridW: 1, gridH: 1 },
  { id: "E29", name: "송하요", gridX: 18, gridY: 23, gridW: 1, gridH: 1 },
  { id: "F13", name: "송화도예", gridX: 20, gridY: 11, gridW: 1, gridH: 1 },
  { id: "E8", name: "수니공방", gridX: 18, gridY: 6, gridW: 1, gridH: 1 },
  { id: "E30", name: "수도예", gridX: 17, gridY: 24, gridW: 1, gridH: 1 },
  { id: "C11", name: "수제차전수관", gridX: 12, gridY: 11, gridW: 1, gridH: 1 },
  { id: "H24", name: "수향(대경팔공공예협동조합)", gridX: 28, gridY: 23, gridW: 2, gridH: 1 },
  { id: "A18", name: "순천대학교 (사)고려천태국제선차 연구보존회", gridX: 5, gridY: 14, gridW: 1, gridH: 1 },
  { id: "E6", name: "스튜디오 세온", gridX: 18, gridY: 5, gridW: 1, gridH: 1 },
  { id: "E19", name: "슬우재", gridX: 17, gridY: 15, gridW: 1, gridH: 1 },
  { id: "A44", name: "승설재·무이성", gridX: 31, gridY: 16, gridW: 1, gridH: 4 },
  { id: "F29", name: "심곡요", gridX: 20, gridY: 23, gridW: 1, gridH: 1 },
  { id: "G23", name: "아람드리", gridX: 24, gridY: 21, gridW: 2, gridH: 1 },
  { id: "H12", name: "아망시 프리미엄 티라운지", gridX: 29, gridY: 12, gridW: 1, gridH: 1 },
  { id: "A33", name: "안동착한농장 프로폴리스 茶", gridX: 19, gridY: 26, gridW: 1, gridH: 1 },
  { id: "D26", name: "알천도예", gridX: 15, gridY: 20, gridW: 1, gridH: 1 },
  { id: "A30", name: "언담", gridX: 12, gridY: 26, gridW: 1, gridH: 1 },
  { id: "F21", name: "언양도예", gridX: 20, gridY: 17, gridW: 1, gridH: 1 },
  { id: "E5", name: "엄기순 금속전", gridX: 17, gridY: 5, gridW: 1, gridH: 1 },
  { id: "E10", name: "여송도예", gridX: 18, gridY: 8, gridW: 1, gridH: 1 },
  { id: "G27", name: "여원", gridX: 24, gridY: 24, gridW: 2, gridH: 1 },
  { id: "F7", name: "연세라믹", gridX: 20, gridY: 6, gridW: 1, gridH: 1 },
  { id: "C2", name: "연우제다", gridX: 11, gridY: 5, gridW: 1, gridH: 1 },
  { id: "A27", name: "연으로 만드는 힐링푸드 두레연구품당", gridX: 6, gridY: 26, gridW: 2, gridH: 1 },
  { id: "F20", name: "연화도방", gridX: 21, gridY: 15, gridW: 1, gridH: 1 },
  { id: "D31", name: "영남요", gridX: 15, gridY: 23, gridW: 1, gridH: 1 },
  { id: "E17", name: "예인요", gridX: 17, gridY: 14, gridW: 1, gridH: 1 },
  { id: "H4", name: "예평", gridX: 27, gridY: 5, gridW: 2, gridH: 2 },
  { id: "C20", name: "오름오르다", gridX: 11, gridY: 18, gridW: 1, gridH: 1 },
  { id: "A46", name: "오차연각", gridX: 31, gridY: 13, gridW: 1, gridH: 1 },
  { id: "A34", name: "옻칠채", gridX: 20, gridY: 26, gridW: 1, gridH: 1 },
  { id: "A35", name: "와락공방", gridX: 22, gridY: 26, gridW: 1, gridH: 1 },
  { id: "A2", name: "완도 청해진다원", gridX: 6, gridY: 4, gridW: 1, gridH: 1 },
  { id: "D21", name: "우곡요", gridX: 14, gridY: 17, gridW: 1, gridH: 1 },
  { id: "F8", name: "우기세라믹", gridX: 21, gridY: 6, gridW: 1, gridH: 1 },
  { id: "A32", name: "우기원", gridX: 16, gridY: 26, gridW: 2, gridH: 1 },
  { id: "E11", name: "우림도예", gridX: 17, gridY: 9, gridW: 1, gridH: 1 },
  { id: "B22", name: "욱산도헌", gridX: 9, gridY: 20, gridW: 1, gridH: 1 },
  { id: "C9", name: "웃차", gridX: 12, gridY: 9, gridW: 1, gridH: 1 },
  { id: "A49", name: "원유전통", gridX: 31, gridY: 2, gridW: 1, gridH: 3 },
  { id: "B5", name: "유기농 원당제다원", gridX: 9, gridY: 5, gridW: 1, gridH: 1 },
  { id: "E3", name: "이아뜰리에", gridX: 17, gridY: 3, gridW: 1, gridH: 1 },
  { id: "F23", name: "이치헌도예연구소", gridX: 20, gridY: 18, gridW: 1, gridH: 1 },
  { id: "D1", name: "일구다&요산당", gridX: 14, gridY: 2, gridW: 1, gridH: 1 },
  { id: "H17", name: "일삼차(壹叁茶) 武夷岩茶", gridX: 27, gridY: 18, gridW: 1, gridH: 1 },
  { id: "F22", name: "임의섭도예작업장", gridX: 21, gridY: 17, gridW: 1, gridH: 1 },
  { id: "A37", name: "자연으로 옹크씨", gridX: 26, gridY: 26, gridW: 1, gridH: 1 },
  { id: "F1", name: "자연을담다", gridX: 20, gridY: 2, gridW: 1, gridH: 1 },
  { id: "A19", name: "장흥청태전(장흥다원)", gridX: 6, gridY: 14, gridW: 1, gridH: 1 },
  { id: "G4", name: "재단법인 하동차&바이오진흥원", gridX: 23, gridY: 6, gridW: 2, gridH: 1 },
  { id: "C8", name: "쟈드리 TEA SHOP", gridX: 11, gridY: 9, gridW: 1, gridH: 1 },
  { id: "A31", name: "정가로이", gridX: 14, gridY: 26, gridW: 2, gridH: 1 },
  { id: "G3", name: "정산당", gridX: 24, gridY: 5, gridW: 2, gridH: 1 },
  { id: "C23", name: "정요", gridX: 12, gridY: 20, gridW: 1, gridH: 1 },
  { id: "F19", name: "정호요", gridX: 20, gridY: 15, gridW: 1, gridH: 1 },
  { id: "A5", name: "제주차농 JEJU CHANONG", gridX: 6, gridY: 9, gridW: 1, gridH: 1 },
  { id: "C22", name: "조선백자", gridX: 11, gridY: 20, gridW: 1, gridH: 1 },
  { id: "D9", name: "조태연가 죽로차", gridX: 14, gridY: 8, gridW: 1, gridH: 1 },
  { id: "H20", name: "주식회사 인센스월드", gridX: 28, gridY: 20, gridW: 2, gridH: 1 },
  { id: "A38", name: "주앤안 (이든갤러리)", gridX: 27, gridY: 26, gridW: 1, gridH: 1 },
  { id: "D5", name: "죽로은침", gridX: 14, gridY: 5, gridW: 1, gridH: 1 },
  { id: "B8", name: "죽림다원", gridX: 8, gridY: 8, gridW: 1, gridH: 1 },
  { id: "H8", name: "죽평", gridX: 29, gridY: 8, gridW: 1, gridH: 1 },
  { id: "G9", name: "지유명차", gridX: 24, gridY: 8, gridW: 2, gridH: 2 },
  { id: "F27", name: "진곡요", gridX: 20, gridY: 21, gridW: 1, gridH: 1 },
  { id: "B6", name: "징광잎차", gridX: 8, gridY: 6, gridW: 1, gridH: 1 },
  { id: "A47", name: "차문화협회", gridX: 31, gridY: 9, gridW: 1, gridH: 4 },
  { id: "D16", name: "차살림", gridX: 15, gridY: 12, gridW: 1, gridH: 1 },
  { id: "G16", name: "차세상(茶世上) / 유산차방(遊山茶訪) 한국총판", gridX: 24, gridY: 14, gridW: 2, gridH: 2 },
  { id: "H2", name: "차우림, 오래된 미래", gridX: 29, gridY: 2, gridW: 1, gridH: 1 },
  { id: "A6", name: "차인연합회", gridX: 1, gridY: 9, gridW: 4, gridH: 1 },
  { id: "C10", name: "찻잎마술/소암 茶", gridX: 11, gridY: 11, gridW: 1, gridH: 1 },
  { id: "C28", name: "채담요", gridX: 11, gridY: 24, gridW: 1, gridH: 1 },
  { id: "G6", name: "천년보이차", gridX: 23, gridY: 8, gridW: 1, gridH: 1 },
  { id: "B3", name: "천보다원", gridX: 9, gridY: 3, gridW: 1, gridH: 1 },
  { id: "A42", name: "천연염색 미주사랑", gridX: 31, gridY: 23, gridW: 1, gridH: 1 },
  { id: "F10", name: "청기백기", gridX: 21, gridY: 8, gridW: 1, gridH: 1 },
  { id: "E22", name: "청담요", gridX: 18, gridY: 17, gridW: 1, gridH: 1 },
  { id: "H22", name: "청도 천연염색연구회 쪽빛나라", gridX: 29, gridY: 21, gridW: 1, gridH: 1 },
  { id: "A39", name: "청도천연염색연구회 감물드리", gridX: 29, gridY: 26, gridW: 1, gridH: 1 },
  { id: "D30", name: "청림도요", gridX: 14, gridY: 23, gridW: 1, gridH: 1 },
  { id: "C5", name: "청석골감로다원", gridX: 12, gridY: 6, gridW: 1, gridH: 1 },
  { id: "E14", name: "청욱요", gridX: 18, gridY: 11, gridW: 1, gridH: 1 },
  { id: "B19", name: "청자, 더 공유 / the0u", gridX: 8, gridY: 18, gridW: 1, gridH: 1 },
  { id: "C15", name: "청학도방", gridX: 12, gridY: 14, gridW: 1, gridH: 1 },
  { id: "H14", name: "취죽진여실", gridX: 29, gridY: 14, gridW: 1, gridH: 1 },
  { id: "F30", name: "침향나무", gridX: 21, gridY: 23, gridW: 1, gridH: 1 },
  { id: "A29", name: "토라", gridX: 11, gridY: 26, gridW: 1, gridH: 1 },
  { id: "B17", name: "토정가 (이조요) since1940", gridX: 8, gridY: 17, gridW: 1, gridH: 1 },
  { id: "A45", name: "투다헌", gridX: 31, gridY: 15, gridW: 1, gridH: 1 },
  { id: "A25", name: "트임&김진욱도예원", gridX: 6, gridY: 22, gridW: 1, gridH: 1 },
  { id: "B15", name: "티 팔래트", gridX: 9, gridY: 12, gridW: 1, gridH: 1 },
  { id: "G2", name: "티하우스 나니", gridX: 23, gridY: 5, gridW: 1, gridH: 1 },
  { id: "C3", name: "티후", gridX: 12, gridY: 5, gridW: 1, gridH: 1 },
  { id: "G13", name: "틴지오브소울", gridX: 24, gridY: 12, gridW: 2, gridH: 1 },
  { id: "G20", name: "포담 티하우스", gridX: 23, gridY: 20, gridW: 2, gridH: 1 },
  { id: "D32", name: "포암요", gridX: 14, gridY: 24, gridW: 1, gridH: 1 },
  { id: "A43", name: "풀과빛 (청도군 천연염색 연구회)", gridX: 31, gridY: 20, gridW: 1, gridH: 1 },
  { id: "H18", name: "하나실크로드티", gridX: 28, gridY: 17, gridW: 2, gridH: 2 },
  { id: "D8", name: "하동 휴심선차", gridX: 15, gridY: 6, gridW: 1, gridH: 1 },
  { id: "C4", name: "하동아낙(LADY HADONG)", gridX: 11, gridY: 6, gridW: 1, gridH: 1 },
  { id: "A4", name: "한국제다", gridX: 6, gridY: 7, gridW: 1, gridH: 2 },
  { id: "A21", name: "한국토기", gridX: 5, gridY: 15, gridW: 1, gridH: 1 },
  { id: "B14", name: "한국티산업경영연구원 - 차그리다", gridX: 8, gridY: 12, gridW: 1, gridH: 1 },
  { id: "D10", name: "한밭제다 차공간", gridX: 15, gridY: 8, gridW: 1, gridH: 1 },
  { id: "B28", name: "한세은 도예공방", gridX: 9, gridY: 24, gridW: 1, gridH: 1 },
  { id: "H3", name: "한차원", gridX: 29, gridY: 3, gridW: 1, gridH: 1 },
  { id: "D19", name: "해너울", gridX: 14, gridY: 15, gridW: 1, gridH: 1 },
  { id: "G11", name: "향적당", gridX: 24, gridY: 11, gridW: 2, gridH: 1 },
  { id: "A22", name: "헬스베버리지", gridX: 6, gridY: 15, gridW: 1, gridH: 1 },
  { id: "D27", name: "현암요", gridX: 14, gridY: 21, gridW: 1, gridH: 1 },
  { id: "A3", name: "현암제다", gridX: 6, gridY: 5, gridW: 1, gridH: 1 },
  { id: "D4", name: "혜림茶. 혜림농원", gridX: 15, gridY: 3, gridW: 1, gridH: 1 },
  { id: "E31", name: "화경도요", gridX: 18, gridY: 24, gridW: 1, gridH: 1 },
  { id: "C16", name: "황매산다원 허굴산방", gridX: 11, gridY: 15, gridW: 1, gridH: 1 },
  { id: "D3", name: "황아차 용강 녹차", gridX: 14, gridY: 3, gridW: 1, gridH: 1 },
  { id: "B18", name: "황우요", gridX: 9, gridY: 17, gridW: 1, gridH: 1 },
  { id: "E12", name: "효원도예", gridX: 18, gridY: 9, gridW: 1, gridH: 1 },
  { id: "B16", name: "효월", gridX: 8, gridY: 14, gridW: 2, gridH: 2 },
  { id: "E26", name: "효향요", gridX: 17, gridY: 21, gridW: 1, gridH: 1 },
  { id: "A8", name: "휘계차", gridX: 0, gridY: 15, gridW: 1, gridH: 1 },
  { id: "H15", name: "휴다인", gridX: 29, gridY: 15, gridW: 1, gridH: 1 },
  { id: "G28", name: "미배정 부스", gridX: 25, gridY: 24, gridW: 1, gridH: 1 },
  { id: "D28", name: "미배정 부스", gridX: 15, gridY: 21, gridW: 1, gridH: 1 },
  { id: "등록대", name: "등록대", gridX: 17, gridY: 0, gridW: 1, gridH: 1 },
  { id: "무대", name: "메인 무대 (차 시연 및 공연)", gridX: 1, gridY: 18, gridW: 4, gridH: 2 },
  { id: "입구_1", name: "입구", gridX: 8, gridY: 0, gridW: 1, gridH: 1 },
  { id: "입구_2", name: "입구", gridX: 26, gridY: 0, gridW: 1, gridH: 1 },
  { id: "출구_1", name: "출구", gridX: 9, gridY: 0, gridW: 1, gridH: 1 },
  { id: "출구_2", name: "출구", gridX: 27, gridY: 0, gridW: 1, gridH: 1 },
];

// Helper function to map booth ID to grid coordinates and cell dimensions
function getBoothGrid(id) {
  const booth = EXHIBITORS_DATA.find(b => b.id === id);
  if (!booth) return null;
  return {
    gridX: booth.gridX,
    gridY: booth.gridY,
    gridW: booth.gridW,
    gridH: booth.gridH
  };
}

// Helper function to convert grid units to pixels
function getBoothCoordinatesForGrid(gridX, gridY, gridW, gridH) {
  const COL_UNIT = 28; // cell width (26px) + gap (2px)
  const ROW_UNIT = 22; // cell height (20px) + gap (2px)
  const margin_left = 32;
  const margin_top = 23;
  
  const x = margin_left + gridX * COL_UNIT;
  // gridY = 26 is Row 1 (top of SVG), gridY = 0 is Row 27 (bottom of SVG)
  const y = margin_top + (26 - (gridY + gridH - 1)) * ROW_UNIT;
  
  const width = gridW * 26 + (gridW - 1) * 2;
  const height = gridH * 20 + (gridH - 1) * 2;
  
  return { x, y, width, height, gridX, gridY, gridW, gridH };
}

// Generate coordinates dynamically based on booth ID
function getBoothCoordinates(id) {
  const grid = getBoothGrid(id);
  if (!grid) return null;
  return getBoothCoordinatesForGrid(grid.gridX, grid.gridY, grid.gridW, grid.gridH);
}

// Helper to dynamically extract section from first letter of ID (A-H), defaulting to 'SPECIAL'
function getBoothSection(id) {
  const firstChar = id.charAt(0);
  return (firstChar >= 'A' && firstChar <= 'H') ? firstChar : 'SPECIAL';
}

// Compile final list with coordinates for app.js rendering
const DEFAULT_EXHIBITORS = EXHIBITORS_DATA.map(booth => {
  const coords = getBoothCoordinatesForGrid(booth.gridX, booth.gridY, booth.gridW, booth.gridH);
  return {
    ...booth,
    section: getBoothSection(booth.id),
    ...coords
  };
});

// Pillar Coordinates (Located on the grid map)
const PILLARS = [
  { "gridX": 5, "gridY": 18, "gridW": 1, "gridH": 1 },
  { "gridX": 5, "gridY": 9, "gridW": 1, "gridH": 1 }
].map(p => {
  const coords = getBoothCoordinatesForGrid(p.gridX, p.gridY, p.gridW, p.gridH);
  return { ...p, ...coords };
});
